---
title: "Cricket Dashboard"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    html_document: default
    css: styles.css
---


```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(plotly)
library(dplyr)
library(googleVis)
odi = read.csv('odi-batting.csv',stringsAsFactors = FALSE)
odi$Year = as.numeric(format.Date(as.Date(odi$MatchDate,"%m-%d-%Y"),"%Y"))
odi$Country = as.factor(odi$Country)
odi$Versus = as.factor(odi$Versus)
```


Summary of Top 10 Players{data-icon="fa-list"}
=======================================================================

select the country {.sidebar data-width=150}
-----------------------------------------------------------------------

```{r}
selectInput(inputId = 'Country',label = 'Choose Country', 
            choices = as.character(unique(odi$Country)),
            selected = 'India')

selectInput(inputId = 'opponent',label = 'Choose Opponent', 
            choices = c('All',as.character(unique(odi$Versus))),
            selected = 'All')
```

Row{data-height=100}
-----------------------------------------------------------------------

### *Total Number of Matches*
```{r}
renderValueBox({
  data = {
    if(input$opponent == 'All') {
    data1 = odi %>% filter(Country == input$Country)
  }else{
    data1 = odi %>% filter(Country == input$Country, Versus == input$opponent)
  }
    data1
    }

Total_match = data %>% summarise(n = n_distinct(MatchDate))
valueBox(Total_match, color = "green", icon = 'fa-flag')
  })
```

### *Total Runs*  
```{r}
renderValueBox({
  data = {
    if(input$opponent == 'All') {
    data1 = odi %>% filter(Country == input$Country)
  }else{
    data1 = odi %>% filter(Country == input$Country, Versus == input$opponent)
  }
    data1
    }
Total_runs = data %>% summarise(round(sum(Runs,na.rm = 1),2))
valueBox(Total_runs, color = "red", icon = 'fa-hand-o-left')
 })
```

### *Average Score Rate*
```{r}
renderValueBox({
  data = {
    if(input$opponent == 'All') {
    data1 = odi %>% filter(Country == input$Country)
  }else{
    data1 = odi %>% filter(Country == input$Country, Versus == input$opponent)
  }
    data1
    }
avg_score_rate = data %>% summarise(round(mean(ScoreRate,na.rm = 1),2))
valueBox(avg_score_rate, color = "blue", icon = 'fa-line-chart')
  })
```

###
```{r,fig.align='center',fig.pos="h"}
  renderGauge({
  data = {
    if(input$opponent == 'All') {
    data1 = odi %>% filter(Country == input$Country)
  }else{
    data1 = odi %>% filter(Country == input$Country, Versus == input$opponent)
  }
    data1
    }
avg_score_rate = as.numeric(data %>% summarise(round(mean(ScoreRate,na.rm = 1),2)))

avg = as.numeric(odi %>% summarise(round(mean(ScoreRate,na.rm = 1),2)))
Q = as.numeric(quantile(odi$ScoreRate,probs = c(0,0.3,0.7,1),na.rm = TRUE))
gauge(avg_score_rate,
      min = Q[1],max = Q[4],label = "Score Rate Gauge",
      gaugeSectors(success = c(Q[2],Q[3]),
                              warning = c(Q[1],Q[2]-0.01),
                              danger = c(Q[3]+0.01,Q[4]))
      )
 })
```

Row{data-height=500}
-----------------------------------------------------------------------

### **Performance of top 10 players**

```{r,fig.height=200}
theme_set(theme_bw())
renderPlot({
  data = {
    if(input$opponent == 'All'){
      data1 = odi %>% filter(Country == input$Country)
  }else{
      data1 = odi %>% filter(odi$Country==input$Country, odi$Versus == input$opponent)
  }
  data1
}
 
  ggplot(data %>% group_by(Player) %>%
           summarise(tot_runs = sum(Runs,na.rm = 1)) %>% 
           arrange(-tot_runs) %>% head(10),
         aes(reorder(Player,desc(tot_runs)),tot_runs)) + 
    geom_bar(stat = 'identity',width = 0.5, fill = "purple", color = "black") +
    geom_text(aes(label = tot_runs), vjust = -0.4) + 
    labs(x = '', y = 'Runs') +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.7, size = 10, hjust = 0.01, color = "black"),
          axis.ticks = element_blank(),
          panel.background = element_rect(fill = "gray90"),
          plot.background = element_rect(fill = "gray90"),
          panel.grid = element_blank(),
          panel.border = element_blank(),
          axis.text.y = element_blank())
})
```


Row{data-height=500}

-----------------------------------------------------------------------

### **Tabular Representation**
```{r}
library(knitr)
DT::renderDataTable({
  data ={
    if(input$opponent == 'All'){
      data1 = odi %>% filter(Country == input$Country)
    }else{
      data1 = odi %>% filter(Country == input$Country, Versus == input$opponent)
    }
    data1
  }
  
d1 =  data %>% group_by(Year,Country,Versus) %>% 
                  summarise(Tot_match = n_distinct(MatchDate),
                            Tot_runs = sum(Runs),
                            avg_scr_rate = round(mean(ScoreRate),2))

  DT::datatable(d1,options = list(pageLength = 5,selected = c(5,10),mode = "multiple"),
                fillContainer = TRUE)
})
```


Map 1{data-icon="fa-map-marker" data-navmenu="Map"}
=================================================================

row
-----------------------------------------------------------------------

### **The highest Score rate and highest Runs for each country**


```{r}
#create a ui interaction:
uiOutput("dynamic1")

#render the ui:
output$dynamic1 <- renderUI({
   htmlOutput("myTable")
 })

#plot the chart
output$myTable =
renderGvis({
  
  data1 = odi
  
  gvisGeoChart(data = data1 %>%
                 group_by(Country) %>% 
                 summarise(highest_runs = max(Runs,na.rm = 1),
                           highest_score_rate = max(ScoreRate,na.rm = 1)) %>%
                 inner_join(data1,by = c('Country'='Country','highest_runs' = 'Runs')) %>% 
                 inner_join(data1,by = c('Country'='Country','highest_score_rate' = 'ScoreRate')) %>% 
                 select(Country,highest_runs,Player.x,highest_score_rate,Player.y) %>% 
                 mutate(hov = paste('Highest Runs by',Player.x,'Highest Score Rate by',Player.y)),
               
               locationvar = 'Country',
               colorvar = 'highest_runs',
               sizevar = 'highest_score_rate',
               hovervar = 'hov',
               options = list(displayMode='markers',
                              width = 1500,
                              height = 530,
                              backgroundColor="lightblue",
                              colorAxis="{values:[20,80,140,201],colors:[ \'yellow',\'#7CFC00',\'#FF69B4',\'red']}"
                              ))
})
```


Map 2{.tabset .tabset_fade data-icon="fa-map-marker" data-navmenu="Map"}
=================================================================


### **Highest Runs and Highest Score rate for each Country **


```{r}
#create a ui interaction:
uiOutput("dynamic2")

#render the ui:
output$dynamic2 <- renderUI({
   htmlOutput("secondgraph")
 })

#plot the chart

  data2 = odi
  
  g11 = gvisGeoChart(data = data2 %>%
                 group_by(Country) %>% 
                 summarise(highest_runs = max(Runs,na.rm = 1)) %>%
                 inner_join(data2,by = c('Country'='Country','highest_runs' = 'Runs')) %>% 
                 select(Country,highest_runs,Player) %>% 
                 mutate(hov = paste('Highest Runs by',Player)),
               
               locationvar = 'Country',
               colorvar = 'highest_runs',
               hovervar = 'hov',
               options = list(displayMode='regions',
                              width = 620,
                              height = 530,
                              colorAxis = "{values:[20,80,140,201],colors:[ \'yellow',\'#7CFC00',\'#FF69B4',\'red']}",
                              backgroundColor="lightblue"
                              ))

  g12 =  gvisGeoChart(data = data2 %>%
                 group_by(Country) %>% 
                 summarise(highest_score_rate = max(ScoreRate,na.rm = 1)) %>%
                 inner_join(data2,by = c('Country'='Country','highest_score_rate' = 'ScoreRate')) %>% 
                 select(Country,Player,highest_score_rate) %>% 
                 mutate(hov = paste('Highest Score Rate by',Player)),
               
               locationvar = 'Country',
               colorvar = 'highest_score_rate',
               hovervar = 'hov',
               options = list(displayMode='regions',
                              width = 620,
                              height = 530,
                              colorAxis = "{values:[60,200,400,600],colors:[ \'#FFFF00',\'#0000EE',\'#FF3E96',\'#FF4500']}",
                              backgroundColor="lightblue"
                              ))
  
  output$secondgraph =
renderGvis({
  
  gvisMerge(g11,g12,horizontal = TRUE,tableOptions="cellspacing=0.5")
  
  })
```

Motion Chart on Cricket{data-icon="fa-futbol-o"}
=============================================================
Row
----------------------------------------------------------

### **Yearwise Cricket Summary**

```{r}
uiOutput("dyanamic3") 
output$dyanamic3 <- renderUI({
  htmlOutput("motionchart1")
  })

output$motionchart1 = 
  renderGvis({
    data = odi %>% group_by(Year,Country) %>% 
      summarise(total_matches = n(),
                tot_runs = sum(Runs,na.rm = TRUE),
                avg_score_rate = mean(ScoreRate, na.rm = TRUE))# %>% top_n(n=10)
    
    data = as.data.frame(data)
    data$Country1 = data$Country
    
    gvisMotionChart(data,
                    idvar = "Country",timevar = "Year",
                    colorvar = "Country1",
                    sizevar = "total_matches",
                    xvar = "tot_runs", yvar = "avg_score_rate",
                    options = list(height = 500, width = 1000)
                    )
  })
```

